# Generated by Django 3.1.5 on 2021-01-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
